In [1]:
import numpy as np
print("Python list operations:")
a = [1,2,3]
b = [4,5,6]
print("a+b:", a+b)
try:
    print(a*b)
except TypeError:
    print("a*b has no meaning for Python lists")
print()
print("numpy array operations:")
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a+b:", a+b)
print("a*b:", a*b)
"""
Python list operations:
a+b: [1, 2, 3, 4, 5, 6]
a*b has no meaning for Python lists
numpy array operations:
a+b: [5 7 9]
a*b: [ 4 10 18]
"""

Python list operations:
a+b: [1, 2, 3, 4, 5, 6]
a*b has no meaning for Python lists

numpy array operations:
a+b: [5 7 9]
a*b: [ 4 10 18]


'\nPython list operations:\na+b: [1, 2, 3, 4, 5, 6]\na*b has no meaning for Python lists\nnumpy array operations:\na+b: [5 7 9]\na*b: [ 4 10 18]\n'

In [4]:
"""ArithmeticError
NumPy’s ndarrays also support applying functions along these axes in intuitive
ways. For example, summing along axis 0 (the rows for a 2D array) essentially
“collapses the array” along that axis, returning an array with one less dimension
than the original array; for a 2D array, this is equivalent to summing each
column

a:
[[1 2]
[3 4]]
a.sum(axis=0): [4 6]
a.sum(axis=1): [3 7]

"""
print('a:')
print(a)

a = np.array([[1,2],[3,4]])

print('a.sum(axis=0):', a.sum(axis=0))
print('a.sum(axis=1):', a.sum(axis=1))

a:
[1 2 3]
a.sum(axis=0): [4 6]
a.sum(axis=1): [3 7]


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 1)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Instantiate the network, loss function, and optimizer
model = SimpleNN()
criterion = nn.MSELoss()  # Mean Squared Error Loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Stochastic Gradient Descent

# Dummy data for demonstration
inputs = torch.randn(10, 10)  # 10 samples, each with 10 features
targets = torch.randn(10, 1)  # 10 target values

# Training loop
num_epochs = 10
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(inputs)
    loss = criterion(outputs, targets)
    
    # Backward pass
    optimizer.zero_grad()  # Clear previous gradients
    loss.backward()        # Compute gradients
    
    # Print gradients
    print(f'Epoch {epoch+1}/{num_epochs}')
    for name, param in model.named_parameters():
        if param.grad is not None:
            print(f'Gradient of {name}: {param.grad}')
    
    # Update weights
    optimizer.step()       # Update weights
    
    print(f'Loss: {loss.item():.4f}\n')

# Print updated parameters
for name, param in model.named_parameters():
    print(f'Updated parameter {name}: {param.data}')

Epoch 1/10
Gradient of fc1.weight: tensor([[ 4.0289e-02, -2.5814e-02, -8.6967e-03,  1.4494e-03,  2.1490e-02,
         -2.0458e-02, -1.4004e-02, -3.2003e-02,  1.3028e-02,  1.6742e-02],
        [-3.9019e-02,  6.5033e-03, -2.3343e-02,  2.6206e-02, -1.8978e-02,
          9.1642e-03,  1.6511e-02,  9.5346e-03,  1.6607e-02, -3.1682e-02],
        [ 2.4201e-02,  5.3094e-03, -2.1423e-02, -1.5265e-02, -6.2220e-03,
          2.9077e-03,  5.8574e-03, -1.4923e-02,  1.0308e-02,  3.0197e-02],
        [ 1.0867e-02, -4.7550e-03, -2.6609e-03,  3.5946e-03,  6.1917e-03,
          8.3462e-03,  1.0277e-02, -5.0696e-03, -6.2430e-03,  7.5297e-03],
        [ 3.0253e-03,  1.8307e-03,  3.7559e-02,  1.0410e-03, -1.9335e-02,
         -1.7016e-02,  5.9678e-03,  3.3609e-02, -4.7496e-02,  6.7718e-03],
        [ 2.0939e-03,  7.7927e-04, -6.7727e-03, -9.6569e-03,  9.9193e-03,
          9.1303e-03, -5.5210e-04, -9.7965e-03,  1.0135e-02,  4.4355e-03],
        [ 3.4213e-02,  2.5031e-03,  7.4754e-03, -4.9402e-03, -5.0675e-0

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

# Sample labels (3 classes)
labels = torch.tensor([0, 1, 2, 1])  # Example: 4 samples, classes 0, 1, 2, 1

# One-hot encode the labels
one_hot_labels = F.one_hot(labels, num_classes=3)
print("One-hot encoded labels:")
print(one_hot_labels)

# Define a simple neural network for image classification
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.fc = nn.Linear(10, 3)  # Assuming 10 features, 3 output classes
    
    def forward(self, x):
        return self.fc(x)

# Instantiate the network, loss function, and optimizer
model = SimpleCNN()
criterion = nn.CrossEntropyLoss()  # Cross-entropy loss expects raw logits
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Dummy data for demonstration (4 samples, 10 features)
inputs = torch.randn(4, 10)

# Forward pass
outputs = model(inputs)

# Compute loss using original labels (CrossEntropyLoss combines Softmax and loss calculation)
loss = criterion(outputs, labels)
print(f"Loss: {loss.item()}")

# Backward pass and optimization
optimizer.zero_grad()  # Clear previous gradients
loss.backward()        # Compute gradients
optimizer.step()       # Update weights


One-hot encoded labels:
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 1, 0]])
Loss: 1.2579045295715332
